-- 코드를 입력하세요
SELECT A.FLAVOR
FROM FIRST_HALF A LEFT JOIN ICECREAM_INFO B
    ON A.FLAVOR = B.FLAVOR
WHERE B.INGREDIENT_TYPE = 'fruit_based'
GROUP BY A.FLAVOR
HAVING SUM(A.TOTAL_ORDER) >= 3000
ORDER BY SUM(A.TOTAL_ORDER) DESC
