-- 코드를 입력하세요
SELECT A.TITLE,
       B.BOARD_ID,
       B.REPLY_ID,
       B.WRITER_ID,
       B.CONTENTS,
       DATE_FORMAT(B.CREATED_DATE,'%Y-%m-%d')
FROM USED_GOODS_BOARD AS A
    RIGHT JOIN USED_GOODS_REPLY AS B
    ON B.BOARD_ID = A.BOARD_ID 
WHERE YEAR(A.CREATED_DATE) = 2022 AND MONTH(A.CREATED_DATE) = 10    
ORDER BY B.CREATED_DATE ASC , TITLE ASC